rm(list=ls())
library(here)
library(childesr)
library(dplyr)
library(wordcloud)
library(ggplot2)
library(tidyr)
library(purrr)
library(stringr)
library(quanteda)
library(irlba)
library(spacyr)
library(tidyverse)
source(here::here("02Script", "03RoleMap.R"))

